DROP TABLE IF EXISTS volunteer;
DROP TABLE IF EXISTS customers;

CREATE TABLE volunteer (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  email TEXT NOT NULL,
  areas TEXT NOT NULL
  );

CREATE TABLE customers (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  neighborhood TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  preference INTEGER NOT NULL,
  type_of_assistance TEXT NOT NULL,
  payment INTEGER NOT NULL,
  served INTEGER
  );