DROP TABLE IF EXISTS volunteer;
DROP TABLE IF EXISTS customer;


CREATE TABLE customer (
id INTEGER PRIMARY KEY AUTOINCREMENT,
created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
email TEXT NOT NULL,
phone TEXT NOT NULL,
preference INTEGER,
neighborhood TEXT NOT NULL,
assistancetype TEXT NOT NULL,
payment INTEGER,
served INTEGER
);


CREATE TABLE volunteer (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  email TEXT NOT NULL,
  areas TEXT NOT NULL
  );